Add Jinja whitespace control
open-telemetry/weaver pull request #224
Opened 2024-06-27 13:15 UTC by joaopgrassi

Closes #220

I added the new properties to the existing struct `TemplateSyntax` but I'm not so convinced that's the best place. I can see how it makes sense as the "Jinja config things" but 🤔. I'm open to suggestions. Maybe a different struct to configure jinja environment "in general"? Or maybe rename `TemplateSyntax` to something else, so it not only contain syntax things but general Jinja settings?

2024-06-27 14:50 UTC, joaopgrassi commented
weird sometimes the test fails also on my machine for the line end of the file. I will look into it

2024-06-27 15:56 UTC, lquerel requested changes
Instead of integrating it into 'TemplateSyntax', I propose creating a separate structure in parallel that we could name 'WhitespaceControl', containing the two fields you created. Otherwise your PR LGTM. Thanks!

2024-06-28 12:38 UTC, lquerel approved these changes
Just a few minor modifications to make, but otherwise, it seems ready to be merged.

2024-06-28 12:38 UTC, lquerel commented on crates/weaver_forge/src/config.rs
> +    /// Configures the behavior of the first newline after a block.
This line is probably a leftover from a copy/paste.

2024-06-28 12:38 UTC, lquerel commented on crates/weaver_forge/src/config.rs
> +    #[serde(default = "default_trim_blocks")]
Since you have provided an explicit implementation of the Default trait, these individual declarations are redundant.

2024-06-28 12:38 UTC, lquerel commented on crates/weaver_forge/src/config.rs
> +fn default_trim_blocks() -> bool {
See my previous comment on the Default trait. These functions can be removed.

2024-06-28 13:00 UTC, trisch-me commented on crates/weaver_forge/src/config.rs
> +    #[serde(default = "default_trim_blocks")]
I thought if we want default to be false/0/empty string etc we don't need to define anything as it's default behaviour

2024-06-28 14:26 UTC, jsuereth approved these changes
I echo @lquerel's comments on default trait.  Once that's cleaned up we can merge.

2024-06-28 14:46 UTC, joaopgrassi commented
If I got it right, I don't need the defaults annotations and functions, and I also removed the constructor. Sorry still very noob in Rust :D. Hope it is alright now.

2024-06-28 19:18 UTC, trisch-me approved these changes

2024-07-01 14:52 UTC, joaopgrassi commented
Not sure why the build is stuck? 🤔. I don't have permission to retry it.

2024-07-01 15:35 UTC, trisch-me commented
it's not stuck, I think it's because your test has failed

2024-07-02 11:54 UTC, merged